dependencies {
    implementation(project(":components:circuit-breaker-support"))
    implementation(project(":components:discovery-support"))
    implementation(project(":components:rest-support"))
    implementation(project(":components:test-support"))
    implementation(project(":components:log-support"))
}
