dependencies {
    implementation(project(":components:jdbc-support"))
    implementation(project(":components:redis-support"))
    implementation(project(":components:rest-support"))

    implementation("com.zaxxer:HikariCP:$hikari_version")
    implementation("com.mysql:mysql-connector-j:$mysql_connector_version")
    implementation("redis.clients:jedis:$jedis_version")
}

test {
    dependsOn(
        ":applications:anime-server:jar",
        ":applications:poll-server:jar",
    )
}
