rootProject.name = "malchart"

include "applications:discovery-server"
include "applications:integration"
include "applications:anime-server"
include "applications:poll-server"
include "applications:mal-server"
include "applications:gateway-server"

include "components:circuit-breaker-support"
include "components:discovery"
include "components:discovery-support"
include "components:jdbc-support"
include "components:redis-support"
include "components:rest-support"
include "components:test-support"
include "components:anime"
include "components:poll"
include "components:mal-support"
include "components:mal"
include "components:log-support"
include "components:gateway"
